# Generated by Django 5.2.17 on 2026-09-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_alter_course_id_alter_enrollment_id_alter_faq_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='processed', max_length=50)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Razorpay Webhook Event',
                'verbose_name_plural': 'Razorpay Webhook Events',
                'ordering': ['-processed_at'],
            },
        ),
    ]
